<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('roles')->insert([
            'name' => "superadmin",
            'display_name' => "SuperAdmin",
            'Wifi_Users' => 1,
            'Wifi_Router' => 1,
            'Location' => 1,
            'Distributor' => 1,
            'Franchise' => 1,
            'Internet_Plan_Setting' => 1,
            'Internet_Plan_View' => 1,
            'Payout_Setting' => 1,
            'Payout_Log' => 1,
            'Payment_Setting' => 1,
            'Payment_Log' => 1,
            'Payout_Log_Process' => 1,
            'Leads' => 1,
            'Add_Leads' => 1,
            'SMS_Gateway' => 1,
            'SMS_Template' => 1,
            'Mail_Server' => 1,
            'Email_Template' => 1,
            'Network_Setting' => 1,
            'role_management' => 1,
            'Add_PDOA' => 1,
            'PDOA_Management' => 1,
            'PDOA_Plan' => 1,
            'staff_Management' => 1,
            'WiFi_Router_Models' => 1,
            'Products' => 0,
            'Product_Management' => 1,
            'Process_Product' => 1,
            'Cart' => 1,
            'required' => 1,
        ]);
        DB::table('roles')->insert([
            'name' => "admin",
            'display_name' => "Admin",
            'Wifi_Users' => 1,
            'Wifi_Router' => 1,
            'Location' => 1,
            'Distributor' => 1,
            'Franchise' => 1,
            'Internet_Plan_Setting' => 0,
            'Internet_Plan_View' => 1,
            'Payout_Setting' => 1,
            'Payout_Log' => 1,
            'Payment_Setting' => 1,
            'Payment_Log' => 1,
            'Payout_Log_Process' => 1,
            'Leads' => 1,
            'Add_Leads' => 0,
            'SMS_Gateway' => 1,
            'SMS_Template' => 1,
            'Mail_Server' => 1,
            'Email_Template' => 1,
            'Network_Setting' => 1,
            'role_management' => 0,
            'Add_PDOA' => 0,
            'PDOA_Management' => 0,
            'PDOA_Plan' => 0,
            'staff_Management' => 0,
            'WiFi_Router_Models' => 0,
            'Products' => 0,
            'Product_Management' => 1,
            'Process_Product' => 1,
            'Cart' => 0,
            'required' => 1,
        ]);
        DB::table('roles')->insert([
            'name' => "support",
            'display_name' => "Support",
            'Wifi_Users' => 1,
            'Wifi_Router' => 1,
            'Location' => 1,
            'Distributor' => 1,
            'Franchise' => 1,
            'Internet_Plan_Setting' => 0,
            'Internet_Plan_View' => 1,
            'Payout_Setting' => 0,
            'Payout_Log' => 1,
            'Payment_Setting' => 0,
            'Payment_Log' => 1,
            'Payout_Log_Process' => 1,
            'Leads' => 1,
            'Add_Leads' => 0,
            'SMS_Gateway' => 0,
            'SMS_Template' => 1,
            'Mail_Server' => 0,
            'Email_Template' => 1,
            'Network_Setting' => 0,
            'role_management' => 0,
            'Add_PDOA' => 0,
            'PDOA_Management' => 0,
            'PDOA_Plan' => 0,
            'staff_Management' => 0,
            'WiFi_Router_Models' => 0,
            'Products' => 0,
            'Product_Management' => 1,
            'Process_Product' => 1,
            'Cart' => 0,
            'required' => 1,
        ]);
        DB::table('roles')->insert([
            'name' => "Distributor",
            'display_name' => "Distributor",
            'Wifi_Users' => 0,
            'Wifi_Router' => 0,
            'Location' => 1,
            'Distributor' => 0,
            'Franchise' => 1,
            'Internet_Plan_Setting' => 0,
            'Internet_Plan_View' => 1,
            'Payout_Setting' => 0,
            'Payout_Log' => 1,
            'Payment_Setting' => 0,
            'Payment_Log' => 1,
            'Payout_Log_Process' => 0,
            'Leads' => 0,
            'Add_Leads' => 0,
            'SMS_Gateway' => 0,
            'SMS_Template' => 0,
            'Mail_Server' => 0,
            'Email_Template' => 0,
            'Network_Setting' => 0,
            'role_management' => 0,
            'Add_PDOA' => 0,
            'PDOA_Management' => 0,
            'PDOA_Plan' => 0,
            'staff_Management' => 0,
            'WiFi_Router_Models' => 0,
            'Products' => 1,
            'Product_Management' => 0,
            'Process_Product' => 0,
            'Cart' => 1,
            'required' => 1,
        ]);
        DB::table('roles')->insert([
            'name' => "Franchise",
            'display_name' => "Franchise",
            'Wifi_Users' => 0,
            'Wifi_Router' => 0,
            'Location' => 1,
            'Distributor' => 0,
            'Franchise' => 0,
            'Internet_Plan_Setting' => 0,
            'Internet_Plan_View' => 1,
            'Payout_Setting' => 0,
            'Payout_Log' => 1,
            'Payment_Setting' => 0,
            'Payment_Log' => 1,
            'Payout_Log_Process' => 0,
            'Leads' => 0,
            'Add_Leads' => 0,
            'SMS_Gateway' => 0,
            'SMS_Template' => 0,
            'Mail_Server' => 0,
            'Email_Template' => 0,
            'Network_Setting' => 0,
            'role_management' => 0,
            'Add_PDOA' => 0,
            'PDOA_Management' => 0,
            'PDOA_Plan' => 0,
            'staff_Management' => 0,
            'WiFi_Router_Models' => 0,
            'Products' => 1,
            'Product_Management' => 0,
            'Process_Product' => 0,
            'Cart' => 1,
            'required' => 1,
        ]);

        DB::table('pdoa_plan')->insert([
            'plan_name' => "Demo",
            'price' => 3000,
            'max_wifi_router_count' => 100,
            'status' => 1,
        ]);

        DB::table('pdoas')->insert([
            'id' => "pulse_1_" . date("Y-m-d_H-i-s"),
            'brand_name' => "Pulse WiFi",
            'brand_logo' => "",
            'platform_bg' => "",
            'distributor_fee' => 1000,
            'franchise_fee' => 1000,
            'pdoa_status' => 1,
            'pdoa_plan_id' => 1,
            'domain_name' => "console.pulsewifi.net",
            // 'domain_name' => "pulsetest.cnctdwifi.com",
            'payment_status' => 1,
            'username' => "SuperAdmin",
            'firstname' => "Super",
            'lastname' => "Admin",
            'email' => 'pulsesuper@gmail.com',
            'address' => 'Kamalpur',
            'city' => 'Mongalkote',
            'state' => 'West Bengal',
            'postal_code' => 713147,
            'country' => 'India',
        ]);
 
        DB::table('users')->insert([
            'username' => "SuperAdmin",
            'firstname' => "Kumar",
            'lastname' => "Mrinal",
            'email' => 'pulsesuper@gmail.com',
            'role' => 1,
            'enabled' => 1,
            'password' => Hash::make('superadmin987'),
            'email_verified' => 1,
            'lead_process' => 2,
            'address' => 'Kamalpur',
            'city' => 'Mongalkote',
            'state' => 'West Bengal',
            'postal_code' => 713147,
            'country' => 'India',
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
        ]);
        
        DB::table('mail_server')->insert([
            'name' => "MainServer",
            'sender_name' => "SuperAdmin",
            'sender_email' => "pulsesuper@gmail.com",
            'api_key' => "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",
            'status' => 1,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
        ]);

        DB::table('network_setting')->insert([
            'guestEssid' => "SuperAdmin",
            'freeWiFi' => 1,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
            'freeBandwidth' => 150,
            'freeDailySession' => 60,
            'freeDataLimit' => 500,
            'serverWhitelist' => 'google.com,login.cnctdwifi.com,www.yahoo.com',
            'domainWhitelist' => '.google.com,.cnctdwifi.com,.yahoo.com',
        ]);
        DB::table('payment_setting')->insert([
            'name' => "MainServerPaymentGateway",
            'key' => "rzp_test_j6GuvBBqvdXJVC",
            'secret' => "rbdyKTaZP7IWw6Xi7DTfXdcY",
            'callback_url' => "/api/wifi/order/process-payment",
            'status' => 1,
            'type' => 1,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id
        ]);
        DB::table('users')->insert([
            'username' => "testdistributor",
            'firstname' => "test",
            'lastname' => "distributor",
            'email' => 'testdistributor@gmail.com',
            'role' => 4,
            'enabled' => 1,
            'password' => Hash::make('password'),
            'email_verified' => 1,
            'lead_process' => 2,
            'address' => 'Kamalpur',
            'city' => 'Mongalkote',
            'state' => 'West Bengal',
            'postal_code' => 123123,
            'country' => 'India',
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
        ]);
        DB::table('users')->insert([
            'username' => "testfranchise",
            'firstname' => "test",
            'lastname' => "franchise",
            'email' => 'testfranchise@gmail.com',
            'role' => 5,
            'enabled' => 1,
            'password' => Hash::make('password'),
            'email_verified' => 1,
            'lead_process' => 2,
            'belongs_to' => 2,
            'address' => 'Kamalpur',
            'city' => 'Mongalkote',
            'state' => 'West Bengal',
            'postal_code' => 713147,
            'country' => 'India',
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
        ]);
        DB::table('location')->insert([
            'name' => "testlocation1",
            'owner_id' => 3,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
            'address' => 'Kamalpur',
            'city' => 'Mongalkote',
            'state' => 'West Bengal',
            'postal_code' => 713147,
            'country' => 'India',
        ]);
        DB::table('location')->insert([
            'name' => "testlocation2",
            'owner_id' => 3,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
            'address' => 'Kamalpur',
            'city' => 'Mongalkote',
            'state' => 'West Bengal',
            'postal_code' => 713147,
            'country' => 'India',
        ]);
        DB::table('wifi_router_model')->insert([
            'name'=>'testmodel',
            'description'=>'testmodel',
            'images'=>'',
            'status'=>1,
            'price'=>1000
        ]);
        DB::table('wifi_router')->insert([
            'name'=>'testrouter',
            'mac_address'=>'AA-BB-CC-11',
            'location_id'=>1,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
            'owner_id'=>3,
            'model_id' =>DB::table('location')->get()->first()->id,
            'status'=>1
        ]);
        DB::table('wifi_router')->insert([
            'name'=>'testrouter2',
            'mac_address'=>'AA-BB-CC-22',
            'location_id'=>1,
            'pdoa_id' => DB::table('pdoas')->get()->first()->id,
            'owner_id'=>3,
            'model_id' =>DB::table('location')->get()->first()->id,
            'status'=>1
        ]);


    }
}